name: Run Python Script Weekly

on:
  schedule:
    - cron: "33 6* * *" # Runs at 11:59 PM every Sunday
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.6 # Specify the required Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pymongo
          pip install dnspython

      - name: Run script
        run: |
          python DataScraping/Weather/fetch_climate_data_scheduler.py  # Update with the actual path to your script
