name: Weekly Weather Data Workflow

on:
  schedule:
    - cron: "55 11 * * 1" # Runs at 11:55 PM every Monday
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9 # Specify the required Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pymongo
          pip install dnspython

      - name: Run script
        run: |
          python DataScraping/Weather/fetch_climate_data_scheduler.py  # Update with the actual path to your script
